### PR TITLE
Upgrade to 0.0.65, dynamic-import based requires

### PR DESCRIPTION
**Pull request by borkdude**

### CODE REVIEW

**Comment by borkdude** [comment]
@chr15m nbb 0.0.50+ contains breaking changes with regards to how requires are implemented: JS libs are loaded via dynamic import, which allows it to load ES6 modules. Some node packages now only are offered through ES6 modules, so this was a necessary breaking change.

**Comment by borkdude** [comment]
This is also a possibility: `["twitter-api-v2/dist$TwitterApi" :as TwitterApi]`.

**Comment by chr15m** [comment]
@borkdude thanks for this. Is this the standard across the cljs ecosystem moving forwards?

**Comment by borkdude** [comment]
@chr15m CLJS has no module standard, but this is imposed by the JS world. What happens is that nbb now uses import for loading JS libs. And then you get something like this:

``` clojure
$ node foo.mjs
import termSize from 'term-size';

// similar to:
// import * as termsizeModule from 'term-size';
// let termSize = termSizeModule.default;

import * as fs from 'fs';
// fs exposes both default and all things from default at the top level, so no need to go through default here.

console.log(fs.readFileSync('foo.mjs').toString());
console.log(termSize());

{ columns: 209, rows: 52 }
```

**Comment by borkdude** [comment]
The dollar sign stuff is a new feature in CLJS. https://clojurescript.org/news/2021-04-06-release#_library_property_namespaces

**Comment by chr15m** [comment]
Thanks!

**Pull request merged**
